baseURL = "https://example.org/"
languageCode = "en-us"
title = "Personal Digital Garden"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']
  enableSearch = true

[Params.newsletter]
  title = ""
  description = "A curated weekly digest once a week to your mailbox"

  # Supports buttondown, substack and revue
  provider = "buttondown"

  # Buttondown - URL from share page; Refer: https://blog.buttondown.email/2019/10/11/adding-a-buttondown-subscription-form-to-webflow#getting-your-subscription-url
  # Substack - URL of the newsletter homepage; Example: https://on.substack.com/
  # Revue - Username
  path = "https://buttondown.email/api/emails/embed-subscribe/"



# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
